name: Download and Commit File

on:
    workflow_dispatch:


jobs:
    download-commit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with: 
                ref: ${{ github.head_ref }}

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'

            - name: Download file
              run: |
                curl https://jobs.metro.net/jobsearchRSS.aspx -o docs/jobsearchRSS.xml -k

            - name: Replace https
              run: |
                sed -i 's/https:/http:/g' docs/jobsearchRSS.xml

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: '[Auto] download jobs.metro.net rss'
